name: Deploy

on: 
  push:
  pull_request:
    branches:
      - master
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      
      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run prod
      
      - name: Configure PHP 7.4
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
          
      - name: Install composer dependencies
        run: composer install
        
      - name: Run tests
        run: php artisan test
        
  #get-servers-configuration:
  #  runs-on: ubuntu-latest
  #  needs: run-tests
  #  outputs: 
  #    deployment-servers: ${{ steps.export-deployment-servers.outputs.deployment-servers }}
  #  steps:
  #    - name: Export deployment matrix
  #      id: export-deployment-servers
  #      run: |
  #        JSON="${{ secrets.DEPLOYMENT_SERVERS }}"
  #        JSON="${JSON//'%'/'%25'}"
  #        JSON="${JSON//$'\n'/'%0A'}"
  #        JSON="${JSON//$'\r'/'%0D'}"
  #        echo "::set-output name=deployment-servers::$JSON"
  #deploy-on-server:
  #  runs-on: ubuntu-latest
  #  needs: get-servers-configuration
  #  strategy:
  #    matrix:
  #      server: ${{ fromJson(needs.get-servers-configuration.outputs.deployment-servers) }}
  #  steps:
  #    - run: echo "ok"
