name: Deploy

on: 
  push:
  pull_request:
    branches:
      - master
env:
  CONFIG: ${{ secrets.DEPLOYMENT_SERVERS }}
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      
      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run prod
      
      - name: Configure PHP 7.4
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, zip, sqlite3
  
      - name: Copy ENV file
        shell: bash
        env:
          ENV_FILE: ${{ secrets.LARAVEL_ENV }}
        run: 'echo "$ENV_FILE" > .env'
          
      - name: Install composer dependencies
        run: composer install
        
      - name: Generate key
        run: php artisan key:generate
        
      - name: Run tests
        run: php artisan test
        
  deploy:
    runs-on: ubuntu-latest
    needs: run-tests
    strategy:
      matrix: ${{ fromJSON(env.CONFIG) }}
    steps:
      - run: echo "ok"
